### ISSUE TITLE
Contributing with more examples

### ISSUE THREAD

**Issue by Balastrong** [AnthonyBorton/copilotx#3]
Hello! Is this supposed to be a "personal" repo or are you accepting PRs with some more examples? These months I made some experiments (documented in [4 videos](https://www.youtube.com/playlist?list=PLOQjd5dsGSxLRBUDKZvQhnqOjzNeMUkDj) and [5 articles](https://dev.to/balastrong/series/23030) to keep track) with Copilot X, I can share some of the outcomes here.

Demos include:
- Some code generated entirely with Hey GitHub (in January, before it changed name)
- Unit tests generated by Copilot Chat for 3 js snippets
- Commands from Copilot CLI (with `??` and `git?` mostly)

These days I’m also testing the new `/createWorkspace` but I think there’s still quite some room for improvement on that. The folder structure is fine, but the content of the files… not ready yet, but I still have something to share just in case.

**Comment by AnthonyBorton** [comment]
Hi @Balastrong. Thanks for reaching out. I'd be happy to accept a PR and only ask that you update the readme in your PR to provide context for the examples you would like to include.
Thanks

Anthony

**Comment by Balastrong** [comment]
Sure, thank you!

I created #4 for that :)

**Comment by AnthonyBorton** [comment]
Approved and merged. Thank you again.
